apiVersion: batch/v1
kind: CronJob
metadata:
  name: timekeeper
spec:
  schedule: "*/10 * * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: timekeeper
            image: timekeeper
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - /usr/local/bin/timekeeper
          restartPolicy: OnFailure
